DROP TABLE IF EXISTS User;

CREATE TABLE User (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS Course;

CREATE TABLE Course (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(10) NOT NULL UNIQUE,
    name VARCHAR(20) NOT NULL UNIQUE,
    description VARCHAR(500)
);

DROP TABLE IF EXISTS Enroll;

CREATE TABLE Enroll (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    enroll_date DATE NOT NULL,
    user_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    CONSTRAINT FK_Enroll_USER FOREIGN KEY (user_id) REFERENCES USER(id),
    CONSTRAINT FK_Enroll_COURSE FOREIGN KEY (course_id) REFERENCES COURSE(id)
);

